version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_bd_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_scholarship
    networks:
      - my-network

  spring-app:
    image: openjdk:17
    container_name: scholarship_spring_container
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: ["./mvnw", "spring-boot:run"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_scholarship
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:
