spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_scholarship?createDatabaseIfNotExist=true
    username: root
    password: root
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true